---
- name: Include the Packages for each OS
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install Dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependencies }}"

#---------------------------------------
# Install Code Deploy
#---------------------------------------
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Code Deploy Agent
  when: "'codedeploy-agent' not in ansible_facts.packages"
  block:
    - name: Fetch the CodeDeploy install script
      ansible.builtin.get_url:
        url: "https://aws-codedeploy-{{ ansible_ec2_placement_region }}.s3.{{ ansible_ec2_placement_region }}.amazonaws.com/latest/install"
        dest: /tmp/codedeploy-install
        mode: 0700

    - name: Run the installation script
      become: true
      ansible.builtin.command: /tmp/codedeploy-install auto
