---
- name: Converge
  hosts: all
  vars:
    ansible_ec2_placement_region: us-east-1
  tasks:
    - name: "Include ansible-role-codedeploy-agent"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
