---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the Packages for each OS
      ansible.builtin.include_vars: "../../vars/{{ ansible_os_family }}.yml"

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify Packages
      ansible.builtin.assert:
        that: '"codedeploy-agent" is in ansible_facts.packages'

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services["{{ service_name }}"]

    - name: Assert codedeploy-agent is running
      ansible.builtin.assert:
        that: ansible_facts.services["{{ service_name }}"]["state"] == "running"
