---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the Packages for each OS
      include_vars: "../../vars/{{ ansible_os_family }}.yml"

    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - codedeploy-agent

    - name: Gather service facts
      service_facts:

    - name: Print service facts
      debug:
        var: ansible_facts.services["{{ service_name }}"]

    - name: Assert codedeploy-agent is running
      assert:
        that: ansible_facts.services["{{ service_name }}"]["state"] == "running"
